import path from 'node:path';
import { compileFromFile } from 'json-schema-to-typescript';
import { schemaDirectory } from './schema-manifest.mjs';

const generationOptions = {
  additionalProperties: false,
  enableConstEnums: false,
  style: {
    singleQuote: true,
    trailingComma: 'none'
  },
  unknownAny: true,
  unreachableDefinitions: true
};

export async function generateTypeSource(schemaFile) {
  const schemaPath = path.join(schemaDirectory, schemaFile);
  const versionDirectory = path.dirname(schemaFile).replaceAll(path.sep, '/');
  const bannerComment = `/**\n * Generated from schemas/${versionDirectory}. Do not edit this file directly.\n */`;
  return compileFromFile(schemaPath, { ...generationOptions, bannerComment, cwd: path.dirname(schemaPath) });
}
